## Spring Profiles Active
spring:
  profiles:
    active: dev
  jackson:
    mapper: true
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
  #全局映射器启用缓存
    cache-enabled: false
    #查询时，关闭关联对象即时加载以提高性能
    lazy-loading-enabled: true
    #设置关联对象加载的形态，此处为按需加载字段(加载字段由SQL指定)，不会加载关联表的所有字段，以提高性能
    aggressive-lazy-loading: false
    # 对于未知的SQL查询，允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
    #允许使用列标签代替列名
    useColumnLabel: true
    #允许使用自定义的主键值(比如由程序生成的UUID 32位编码作为键值)，数据表的PK生成策略将被覆盖
    useGeneratedKeys: true
   #对于批量更新操作缓存SQL以提高性能
    defaultExecutorType: simple
    # 数据库超过25000秒仍未响应则超时
    defaultStatementTimeout: 25000

dxhy:
  schedule:
    enterprise_account: account/addDxfw.html
    enterprise_upload: upLoad/saveImg.html
    enterprise_register: enterpriseService/saveWszhyService.html
    enterprise_saveServiceRequest: service/saveServiceRequest.html
    captcha: ele&DB

    provider_userName: jd2016
    provider_password: EleJd2016
    provider_login: index.html
    provider_query: service/queryProvider.html
    provider_qz: enterprise/static/qzResult.html?eId
    provider_uploadImg: upLoad/uploadImg.html
    provider_push: JDPush/pushEnterprise.html
    provider_pushNotice: JDPush/pushNotice.html
    provider_Enterprise: api/enterprise

    provider_Compress: enterprise/static/sendCertEmail/
