#数据库连接配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://jddb-online-7883f6b608234cf6.jcloud.com:3306/dxhy?useUnicode=true&amp;characterEncoding=utf-8
    username: fwsdb
    password: fwsdbFP2016
    type: com.alibaba.druid.pool.DruidDataSource

#logger 日志配置
logging:
  level: info

#企业服务地址
enterprise_project: http://103.237.6.63:8084/enterprise/
#服务商服务地址
provider_project: http://103.237.6.63:8085/provider/