#数据库连接配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://103.237.2.58:3306/dxfws?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

#logger 日志配置
logging:
  level: debug

#启动端口
server:
  port: 8080

#项目服务配置
dxhy:
  schedule:
  #企业服务地址
    enterprise_project: http://localhost:8084/enterprise/
    #服务商服务地址
    provider_project: http://localhost:8084/provider/

