#数据库连接配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://103.237.2.58:3306/dxfws?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: root

#logger 日志配置
logging:
  level: debug

