package com.dxhy.dispatch.manage.dao;

import com.dxhy.dispatch.manage.bean.tables.ApiLog;

public interface ApiLogMapper {



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_log
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    int insertApiLog(ApiLog record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_log
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    ApiLog selectByPrimaryKey(String pk_log);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_log
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    int updateByApiLog(ApiLog record);

}