package com.dxhy.dispatch.manage.bean.tables;

public class ApiLogContent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log_content.pk_log_content
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String pk_log_content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log_content.log_id
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String log_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log_content.dataExchangeId
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String dataExchangeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log_content.content
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log_content.pk_log_content
     *
     * @return the value of api_log_content.pk_log_content
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getPk_log_content() {
        return pk_log_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log_content.pk_log_content
     *
     * @param pk_log_content the value for api_log_content.pk_log_content
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setPk_log_content(String pk_log_content) {
        this.pk_log_content = pk_log_content == null ? null : pk_log_content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log_content.log_id
     *
     * @return the value of api_log_content.log_id
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getLog_id() {
        return log_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log_content.log_id
     *
     * @param log_id the value for api_log_content.log_id
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setLog_id(String log_id) {
        this.log_id = log_id == null ? null : log_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log_content.dataExchangeId
     *
     * @return the value of api_log_content.dataExchangeId
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getDataExchangeId() {
        return dataExchangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log_content.dataExchangeId
     *
     * @param dataExchangeId the value for api_log_content.dataExchangeId
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setDataExchangeId(String dataExchangeId) {
        this.dataExchangeId = dataExchangeId == null ? null : dataExchangeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log_content.content
     *
     * @return the value of api_log_content.content
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log_content.content
     *
     * @param content the value for api_log_content.content
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}