package com.dxhy.dispatch.manage.bean.tables;

import java.util.Date;

public class ApiLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log.pk_log
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String pk_log;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log.appId
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log.version
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log.userName
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log.passWord
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String passWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log.taxpayerId
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String taxpayerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log.enterpriseCode
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String enterpriseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log.dataExchangeId
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String dataExchangeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log.returnCode
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String returnCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log.returnMessage
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String returnMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log.zipCode
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log.encryptCode
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String encryptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log.process_status
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String process_status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log.create_time
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_log.interfaceCode
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    private String interfaceCode;


    @Override
    public String toString() {
        return "ApiLog{" +
                "pk_log='" + pk_log + '\'' +
                ", appId='" + appId + '\'' +
                ", version='" + version + '\'' +
                ", userName='" + userName + '\'' +
                ", passWord='" + passWord + '\'' +
                ", taxpayerId='" + taxpayerId + '\'' +
                ", enterpriseCode='" + enterpriseCode + '\'' +
                ", dataExchangeId='" + dataExchangeId + '\'' +
                ", returnCode='" + returnCode + '\'' +
                ", returnMessage='" + returnMessage + '\'' +
                ", zipCode='" + zipCode + '\'' +
                ", encryptCode='" + encryptCode + '\'' +
                ", process_status='" + process_status + '\'' +
                ", create_time=" + create_time +
                ", interfaceCode='" + interfaceCode + '\'' +
                '}';
    }

    public ApiLog() {
    }

    public ApiLog(String pk_log, String appId, String process_status, Date create_time) {
        this.pk_log = pk_log;
        this.appId = appId;
        this.process_status = process_status;
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log.pk_log
     *
     * @return the value of api_log.pk_log
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getPk_log() {
        return pk_log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log.pk_log
     *
     * @param pk_log the value for api_log.pk_log
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setPk_log(String pk_log) {
        this.pk_log = pk_log == null ? null : pk_log.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log.appId
     *
     * @return the value of api_log.appId
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log.appId
     *
     * @param appId the value for api_log.appId
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log.version
     *
     * @return the value of api_log.version
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log.version
     *
     * @param version the value for api_log.version
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log.userName
     *
     * @return the value of api_log.userName
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log.userName
     *
     * @param userName the value for api_log.userName
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log.passWord
     *
     * @return the value of api_log.passWord
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log.passWord
     *
     * @param passWord the value for api_log.passWord
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log.taxpayerId
     *
     * @return the value of api_log.taxpayerId
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getTaxpayerId() {
        return taxpayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log.taxpayerId
     *
     * @param taxpayerId the value for api_log.taxpayerId
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setTaxpayerId(String taxpayerId) {
        this.taxpayerId = taxpayerId == null ? null : taxpayerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log.enterpriseCode
     *
     * @return the value of api_log.enterpriseCode
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getEnterpriseCode() {
        return enterpriseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log.enterpriseCode
     *
     * @param enterpriseCode the value for api_log.enterpriseCode
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setEnterpriseCode(String enterpriseCode) {
        this.enterpriseCode = enterpriseCode == null ? null : enterpriseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log.dataExchangeId
     *
     * @return the value of api_log.dataExchangeId
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getDataExchangeId() {
        return dataExchangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log.dataExchangeId
     *
     * @param dataExchangeId the value for api_log.dataExchangeId
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setDataExchangeId(String dataExchangeId) {
        this.dataExchangeId = dataExchangeId == null ? null : dataExchangeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log.returnCode
     *
     * @return the value of api_log.returnCode
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log.returnCode
     *
     * @param returnCode the value for api_log.returnCode
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode == null ? null : returnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log.returnMessage
     *
     * @return the value of api_log.returnMessage
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getReturnMessage() {
        return returnMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log.returnMessage
     *
     * @param returnMessage the value for api_log.returnMessage
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setReturnMessage(String returnMessage) {
        this.returnMessage = returnMessage == null ? null : returnMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log.zipCode
     *
     * @return the value of api_log.zipCode
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log.zipCode
     *
     * @param zipCode the value for api_log.zipCode
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log.encryptCode
     *
     * @return the value of api_log.encryptCode
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getEncryptCode() {
        return encryptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log.encryptCode
     *
     * @param encryptCode the value for api_log.encryptCode
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setEncryptCode(String encryptCode) {
        this.encryptCode = encryptCode == null ? null : encryptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log.process_status
     *
     * @return the value of api_log.process_status
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getProcess_status() {
        return process_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log.process_status
     *
     * @param process_status the value for api_log.process_status
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setProcess_status(String process_status) {
        this.process_status = process_status == null ? null : process_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log.create_time
     *
     * @return the value of api_log.create_time
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log.create_time
     *
     * @param create_time the value for api_log.create_time
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_log.interfaceCode
     *
     * @return the value of api_log.interfaceCode
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public String getInterfaceCode() {
        return interfaceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_log.interfaceCode
     *
     * @param interfaceCode the value for api_log.interfaceCode
     *
     * @mbg.generated Mon Jun 26 17:21:17 CST 2017
     */
    public void setInterfaceCode(String interfaceCode) {
        this.interfaceCode = interfaceCode == null ? null : interfaceCode.trim();
    }
}